language: objective-c

before_install: 
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script: 
- xctool clean build -project BPCompatibleAlertControllerDemo/BPCompatibleAlertControllerDemo.xcodeproj -scheme BPCompatibleAlertControllerDemo CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=
- xctool test -project BPCompatibleAlertControllerDemo/BPCompatibleAlertControllerDemo.xcodeproj -scheme BPCompatibleAlertControllerDemo CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=
